INSERT INTO EXPENSE (ID, HOTEL, AMOUNT) VALUES (HIBERNATE_SEQUENCE.NextVal, 'Grand Hotel New York', 595);

INSERT INTO EXPENSE (ID, HOTEL, AMOUNT) VALUES (HIBERNATE_SEQUENCE.NextVal, 'Hotel du pais', 40);

INSERT INTO EXPENSE (ID, HOTEL, AMOUNT) VALUES (HIBERNATE_SEQUENCE.NextVal, 'Verte Hotel', 65);

INSERT INTO EXPENSE (ID, HOTEL, AMOUNT) VALUES (HIBERNATE_SEQUENCE.NextVal, 'Hotel d´or', 321);

INSERT INTO EXPENSE (ID, HOTEL, AMOUNT) VALUES (HIBERNATE_SEQUENCE.NextVal, 'Hotel d´Auvergne', 88);

INSERT INTO EXPENSE (ID, HOTEL, AMOUNT) VALUES (HIBERNATE_SEQUENCE.NextVal, 'Hotel du ciel', 99);